version: "3"

services:     
  back-end:
    container_name: back-end
    build: back-end
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./back-end:/code
    ports:
      - "80:80"
    depends_on:
    - mongo
  ng:
    container_name: front-end
    build: front-end
    ports:
      - "4200:4200"
  mongo:
    image: mongo
    ports:
    - "27017:27017"