# Generated by Django 2.2 on 2019-06-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastebins',
            name='shared',
            field=models.CharField(default='', max_length=200),
        ),
    ]
