# Generated by Django 2.2 on 2019-06-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebins', '0002_pastebins_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastebins',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pastebins',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
