# Generated by Django 2.2 on 2019-06-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebins', '0003_auto_20190602_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastebins',
            name='private',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='pastebins',
            name='public',
            field=models.BooleanField(null=True),
        ),
    ]
